
# Site settings
title: Maydaytyh
email:maydaytyh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hello, everyone.I'm a student majoring in Computer Science. I will post my own thoughts to there.
baseurl: "https://tyhtyhtyh.github.io/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:Mayday_tyh
email:947621178@qq.com
facebook_username:
twitter_username:
github_username:tyhtyhtyh
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:Mayday_tyh

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
# toc_levels: 1..2
